server:
  port: ${PORT:9010}

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/auditoria_db?useSSL=true&allowPublicKeyRetrieval=true}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
