server:
  port: ${PORT:9010}

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/auditoria_db?useSSL=true&allowPublicKeyRetrieval=true}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      show-sql: false
      ddl-auto: none
      format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false

